# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TouchLib Documentation
email: admar@familieschoonen.nl
description: > # this means to ignore newlines until "baseurl:"
  Some examples on how to get started and use TouchLib for (capacitive) touch
  sensors on Arduino and Arduino-like boards.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/admarschoonen/TouchLib" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  admarschoonen

# Build settings
markdown: kramdown
